py_library(
    name = "environment",
    srcs = [
        "observation_parser.py",
        "scheduler_env.py",
        "scheduler_spaces.py",
        "__init__.py",
    ],
    visibility = ["//visibility:public"],
)