py_test(
    name = "observation_parser_tests",
    srcs = [
        "observation_parser_tests.py",
    ],
    deps = [
        "//rl_env/environment:environment",
    ],
    size = "small",
)

py_test(
    name = "scheduler_spaces_tests",
    srcs = [
        "scheduler_spaces_tests.py",
    ],
    deps = [
        "//rl_env/environment:environment",
    ],
    size = "small",
)

py_test(
    name = "scheduler_env_tests",
    srcs = [
        "scheduler_env_tests.py",
    ],
    deps = [
        "//rl_env/environment:environment",
        "//rl_env/threads:threads",
    ],
    size = "small",
)

py_test(
    name = "integration_tests",
    srcs = [
        "integration_tests.py",
    ],
    deps = [
        "//rl_env/environment:environment",
        "//rl_env/threads:threads",
    ],
    size = "small",
)

py_test(
    name = "all_tests",
    srcs = [
        "all_tests.py",
    ],
    deps = [
        "//rl_env/environment:environment",
        "//rl_env/threads:threads",
    ],
    size = "small",
)
