py_test(
    name = "observation_parser_tests",
    srcs = [
        "observation_parser_tests.py",
        "__init__.py",
    ],
    deps = [
        "//rl_env/environment:environment",
    ],
    size = "small",
)